- name: User Playbook
  hosts: all 
  remote_user: opc
  become_method: sudo
  become: yes
  vars_files:
    - 2.users.yml
  tasks:
    - name: Add users
      user:
        name: "{{ user_prefix }}-{{ item.os_user }}"
        shell: /bin/bash
        group: "{{ group }}" 
        append: yes
        state: present
      with_items: "{{ users }}"
      tags:
        - add_users 
    - name: Remove users
      user:
        name: "{{ user_prefix }}-{{ item.os_user }}"
        state: absent 
        remove: yes
      become: true
      with_items: "{{ users }}"
      tags:
        - remove_users
    - name: add group
      group:
        name: "{{ group }}"
        state: present
      become: true
      tags:
        - add_group
